version: '3'
services:
  tp1_server:
    container_name: tp1_server
    image: tp1_server:latest
    entrypoint: python3 /src/server/main.py
    environment:
      PYTHONPATH: /
    networks:
      - tp1_network
    volumes:
      - ./logs:/logs

  tp1_client:
    container_name: tp1_client
    image: tp1_client:latest
    entrypoint: python3 /src/client/main.py
    environment:
      PYTHONPATH: /
    networks:
      - tp1_network
    depends_on:
      - tp1_server

networks:
  tp1_network:
    ipam:
      driver: default
